### ISSUE TITLE
Is this repository open for contributions?

### ISSUE THREAD

**Issue by promovicz** [pkun/klish#1]
I have been using klish for quite some time and have a considerable stash of patches for klish 2.1 and 2.2.

You can find some of my more recent work here:

https://github.com/promovicz/klish

Where should I send patches?

**Comment by pkun** [comment]
Version 2.1 is for bugfix only.
Version 2.2 can accept features.
Send patches to klish mailing list. See 'git format-patch'.

**Comment by promovicz** [comment]
Okay! Many thanks!

I have recently begun porting my changes forward to 2.2, so I am not going to dwell on 2.1.

Some of my changes are simple fixes, others are cleanup. I have also written a new python plugin for which I have added some features such as dynamic commands, but most of that isn't forward-ported yet.
